#!/bin/sh

# Builds the cscope database (cscope.out)

# Run in root of the source code folder

# Generate list of source code files
find "$(pwd)" -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" > cscope.files

# Build database

# -q enables fast symbol lookup
# -R recursive directory search for source files
# -b build the cross reference only
# -i specifies a file of source files

cscope -q -R -b -i cscope.files
mv cscope.out cscope.in.out cscope.po.out ~/
rm cscope.files
