#!/bin/sh

# Builds the cscope database (cscope.out)

# Run in root of the source code folder

# Generate list of source code files
find "$(pwd)" -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" > cscope.files

# Build database
cscope -q -R -b -i cscope.files
mv cscope.out ~/
